import Head from "next/head";
import {
  Grid,
  Typography,
  Container,
  Card,
  CardHeader,
  CardContent,
  CardActions,
  CardActionArea,
  Box,
} from "@mui/material";
import Image from "next/image";
import headshot from "public/headshot.jpg";
import dictionary from "public/assets/dictionary/iphone-12-pro-max--silver.svg";
import connectFour from "public/assets/connect-four/connect-four-macbook-air.svg";
import spaceTourism from "public/assets/space-tourism/space-tourism-surface-studio.svg";
import audiophile from "public/assets/audiophile/audiophile.webp";

import { motion } from "framer-motion";

export default function Home() {
  const data = [
    {
      id: 0,
      title: "Audiophile",
      type: "E-commerce site",
      image: audiophile,
      bgColor: "#d87d4a",
      liveDemo: "https://audiophile-pearl.vercel.app/",
    },
    {
      id: 1,
      title: "Dictionary",
      type: "Dynamic web app",
      image: dictionary,
      bgColor: "#bf7cf2",
      liveDemo: "https://dictionary-jdk.netlify.app/",
    },
    {
      id: 2,
      title: "Space Tourism",
      type: "4-page static website",
      image: spaceTourism,
      bgColor: "#d87d4a",
      liveDemo: "https://space-tourism-jeklnd.netlify.app",
    },
    {
      id: 3,
      title: "Connect Four",
      type: "Web-based game",
      image: connectFour,
      bgColor: "#ffce67",
      liveDemo: "https://connect-four-game.herokuapp.com/",
    },
  ];
  return (
    <>
      <Head>
        <title>Hello, I&apos;m Jesse Krensel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Grid
          container
          rowGap={[2, 2]}
          sx={{ margin: "2rem 0", justifyContent: "space-between" }}
        >
          <Grid
            item
            xs={6}
            sm={6}
            md={8}
            sx={{
              padding: ["0 0.25rem", "0 0.375rem", "0 0.5rem"],
            }}
            component={motion.div}
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.5, ease: "easeIn" }}
          >
            <Card
              sx={{
                height: "100%",
                padding: "1rem",
                borderRadius: "16px",
              }}
              elevation={0}
            >
              <Typography variant="h4">
                Hello, I&apos;m Jesse, a software engineer with a passion for
                the front-end.
              </Typography>
              <Typography variant="h6">
                I enjoy developing beautiful websites and apps with a modern
                stack.
              </Typography>
              <Typography>Contact Me</Typography>
            </Card>
          </Grid>
          <Grid
            item
            xs={6}
            sm={6}
            md={4}
            sx={{
              padding: ["0 0.25rem", "0 0.375rem", "0 0.5rem"],
            }}
            component={motion.div}
            initial={{ x: "2rem", opacity: 0 }}
            whileInView={{ x: 0, opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 1, ease: "linear" }}
          >
            <Box
              sx={{
                position: "relative",
                minHeight: ["300px", "400px"],
              }}
            >
              <Image
                src={headshot}
                fill
                style={{
                  objectFit: "cover",
                  borderRadius: "16px",
                }}
                alt={"ai generated image of Jesse Krensel"}
              ></Image>
              <Box sx={{ position: "relative" }}></Box>
            </Box>
          </Grid>
          {data.map((project) => {
            return (
              <Grid
                item
                xs={12}
                sm={6}
                key={project.id}
                sx={{
                  padding: ["0 0.25rem", "0 0.375rem", "0 0.5rem"],
                }}
                component={motion.div}
                initial={{ y: "2rem", opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                viewport={{ once: true }}
                transition={{
                  delay: project.id === 0 ? 1.5 : 0,
                  ease: "easeIn",
                }}
              >
                <Card
                  elevation={0}
                  sx={{
                    borderRadius: "16px",
                    backgroundColor: `${project.bgColor}60`,
                  }}
                >
                  <CardActionArea
                    href={project.liveDemo}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <CardHeader
                      title={project.title}
                      subheader={project.type}
                    />
                    <CardContent
                      sx={{
                        justifyContent: "center",
                        display: "flex",
                        height: "28rem",
                        padding:
                          project.image === audiophile
                            ? "0"
                            : "0 1rem 1rem 1rem",
                      }}
                    >
                      <Box
                        sx={{
                          position: "relative",
                          width: "100%",
                        }}
                      >
                        <Image
                          src={project.image}
                          alt="project image"
                          fill
                        ></Image>
                      </Box>
                    </CardContent>
                  </CardActionArea>
                </Card>
              </Grid>
            );
          })}
          <Grid
            item
            xs={12}
            sx={{
              padding: ["0 0.25rem", "0 0.25rem", "0 0.5rem"],
            }}
            component={motion.div}
            initial={{ y: "1rem", opacity: 0 }}
            whileInView={{ y: 0, opacity: 1 }}
            viewport={{ once: true }}
            transition={{ ease: "easeIn" }}
          >
            <Card elevation={0} sx={{ borderRadius: "16px" }}>
              <CardActionArea>
                <CardHeader
                  title="Have a project idea?"
                  subheader="Feel free to reach out to for collaborations or to just to say hi"
                />
              </CardActionArea>
            </Card>
          </Grid>
        </Grid>
      </Container>
    </>
  );
}
