import Head from "next/head";
import {
  Grid,
  Typography,
  Container,
  Card,
  CardHeader,
  CardActionArea,
  Box,
  Stack,
  Button,
} from "@mui/material";
import Image from "next/image";
import headshot from "public/photo_headshot.png";
import { motion, useMotionValue, useTransform } from "framer-motion";
import ProjectCard from "@/components/ProjectCard";
import { data } from "@/projectData";
import ReactIcon from "@/icons/ReactIcon";
import NextjsIcon from "@/icons/NextjsIcon";
import HtmlIcon from "@/icons/HtmlIcon";
import CssIcon from "@/icons/CssIcon";
import JavaScriptIcon from "@/icons/JavaScriptIcon";
import MuiIcon from "@/icons/MuiIcon";
import FigmaIcon from "@/icons/FigmaIcon";
import HerokuIcon from "@/icons/HerokuIcon";
import VercelIcon from "@/icons/VercelIcon";
import NetlifyIcon from "@/icons/NetlifyIcon";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import EmailIcon from "@mui/icons-material/Email";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jesse Krensel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <Container sx={{ padding: ["0 2rem", "0 2.5rem"] }}>
        {/* <Box
          sx={{
            backgroundColor: "#000",
            height: "40vh",
            width: "2rem",
          }}
        ></Box> */}
        <Grid
          container
          rowGap={[2, 2]}
          sx={{ margin: "2rem 0", justifyContent: "space-between" }}
        >
          <Grid
            item
            xs={12}
            sm={12}
            md={8}
            sx={{
              padding: ["0 0.25rem", "0 0.375rem", "0 0.5rem"],
            }}
            component={motion.div}
            initial={{ x: -16, opacity: 0 }}
            whileInView={{ x: 0, opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.8 }}
          >
            <Card
              sx={{
                height: "100%",
                padding: "2rem",
                borderRadius: "16px",
                backgroundImage: `radial-gradient(at 44% 0%, #E0F7FA 0px, transparent 50%),
                radial-gradient(at 80% 0%, #E0FFFF 0px, transparent 50%),
                radial-gradient(at 80% 50%, #B2DFDB 0px, transparent 50%),
                radial-gradient(at 0% 100%, #B3E5FC 0px, transparent 50%),
                radial-gradient(at 80% 100%, #CFD8DC 0px, transparent 50%),
                radial-gradient(at 0% 0%, #CFD8DC 0px, transparent 50%)`,
                color: "#21273a",
                perspective: "2000",
              }}
              elevation={0}
            >
              <Stack spacing={1}>
                <Typography variant="subtitle1" sx={{ color: "#3f4864" }}>
                  Hi, my name is
                </Typography>
                <Typography variant="h3" sx={{ fontWeight: "bold" }}>
                  Jesse Krensel.
                </Typography>
                <Typography variant="h4" sx={{ color: "#3f4864" }}>
                  I build for the web using a modern tech stack:
                </Typography>
                <Grid
                  container
                  sx={{
                    display: "flex",
                    gap: "1rem",
                    justifyContent: "center",
                    padding: "2rem",
                  }}
                >
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <HtmlIcon />
                  </Box>
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <CssIcon />
                  </Box>
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <JavaScriptIcon />
                  </Box>
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <ReactIcon />
                  </Box>
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <MuiIcon />
                  </Box>
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <NextjsIcon />
                  </Box>
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <FigmaIcon />
                  </Box>
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <HerokuIcon />
                  </Box>
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <NetlifyIcon />
                  </Box>
                  <Box sx={{ height: "2rem", width: "2rem" }}>
                    <VercelIcon />
                  </Box>
                </Grid>
                <Typography variant="h6" sx={{ color: "#3f4864" }}>
                  My stack and skills grow constantly and with each project
                  requirement.
                </Typography>
                <Box
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    paddingTop: "2rem",
                    gap: "1rem",
                  }}
                >
                  <Typography variant="h5">
                    Hiring? Send me a message on LinkedIn!
                  </Typography>
                  <Button
                    href="https://www.linkedin.com/in/jessekrensel/"
                    rel="noopener noreferrer"
                    target="_blank"
                    sx={{
                      backgroundColor: "#0a66c2",
                      "&:hover": { backgroundColor: "#0a66c2" },
                    }}
                  >
                    <LinkedInIcon
                      sx={{
                        display: "flex",
                        justifyContent: "center",
                        alignItems: "center",
                        color: "#fff",
                      }}
                    />
                  </Button>
                  {/* <Typography
                  // href="mailto:jdkrensel@gmail.com"
                  // target="_blank"
                  // rel="noopener noreferrer"
                  >
                    jdkrensel@gmail.com
                  </Typography> */}

                  {/* <Box>
                    <EmailIcon
                      sx={{
                        display: "flex",
                        justifyContent: "center",
                        alignItems: "center",
                        color: "#0a66c2",
                      }}
                    />
                  </Box> */}
                </Box>
              </Stack>
            </Card>
          </Grid>
          <Grid
            item
            xs={12}
            sm={6}
            md={4}
            sx={{
              padding: ["0 0.25rem", "0 0.375rem", "0 0.5rem"],
            }}
            component={motion.div}
            initial={{ x: "1rem", opacity: 0 }}
            whileInView={{ x: 0, opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.8 }}
          >
            <Box
              sx={{
                position: "relative",
                height: ["448px", "100%"],
                width: "100%",
              }}
            >
              <Image
                src={headshot}
                fill
                style={{
                  objectFit: "cover",
                  borderRadius: "16px",
                }}
                alt={"image of Jesse Krensel"}
              ></Image>
              <Box sx={{ position: "relative" }}></Box>
            </Box>
          </Grid>
          {data.map((project) => {
            return <ProjectCard key={project.id} project={project} />;
          })}
          <Grid
            item
            xs={12}
            sx={{
              padding: ["0 0.25rem", "0 0.25rem", "0 0.5rem"],
            }}
            component={motion.div}
            initial={{ y: "1rem", opacity: 0 }}
            whileInView={{ y: 0, opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
          >
            {/* <Card elevation={0} sx={{ borderRadius: "16px" }}>
              <CardActionArea>
                <CardHeader
                  title="Have a project idea?"
                  subheader="Feel free to reach out to for collaborations or to just to say hi"
                />
              </CardActionArea>
            </Card> */}
          </Grid>
        </Grid>
        <Typography
          variant="body1"
          sx={{ textAlign: "center", padding: "0 0 2rem" }}
        >
          Designed and developed with ❤️ by Jesse Krensel ©{" "}
          {(function () {
            const date = new Date();
            return date.getFullYear();
          })()}
        </Typography>
      </Container>
      {/* <Box
        sx={{ backgroundColor: "#000", height: "1rem", width: "1rem" }}
      ></Box> */}
    </>
  );
}
